baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'artifacts'
theme = 'nightfall'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # escape all raw html, set true to allow

[pagination]
pagerSize = 3

[menu]
  [[menu.header]]
    name = 'about'
    weight = 0
    url = '/about'
  [[menu.header]]
    name = 'posts'
    weight = 1
    url = '/posts'
  [[menu.header]]
    name = 'captures'
    weight = 2
    url = '/captures'

[taxonomies]
tags = "tags"
component = "components"

[params]
user = 'C-1485'
hostname = 'artifacts.io'

showPublishedDate = false
openLinksInNewTab = true
showReadingTime = true
showTags = true

[params.styles]
color = 'red'

[params.author]
name = 'ARTIFACTS'

[[params.social]]
key = 0
name = 'github'

[[params.social]]
key = 1
name = 'email'
